###################################
#### user-configurable options ####
###################################

PREFIX=~
BINDIR=$(wildcard $(PREFIX)/bin)
LIBDIR=$(wildcard $(PREFIX)/lib)

CC=gcc
CXX=g++
CXXFLAGS= -I$(HOME)/projects/tuttepoly/nauty/ -I$(HOME)/projects/tuttepoly/src
CFLAGS = -O2