###################################
#### user-configurable options ####
###################################

PREFIX=~
BINDIR=$(wildcard $(PREFIX)/bin)
LIBDIR=$(wildcard $(PREFIX)/lib)

CC=gcc
CXX=g++
CXXFLAGS= -O2 -I"$(HOME)/projects/tuttepoly/nauty22/" -I"$(HOME)/projects/tuttepoly/src"
# CXXFLAGS= -g -I"$(HOME)/projects/tuttepoly/nauty22/" -I"$(HOME)/projects/tuttepoly/src"

CFLAGS = -O2
