###################################
#### user-configurable options ####
###################################

PREFIX=~
BINDIR=$(wildcard $(PREFIX)/bin)
LIBDIR=$(wildcard $(PREFIX)/lib)

SRCDIR=$(ROOTDIR)

CC=gcc
CXX=g++
CXXFLAGS= -DNDEBUG -O3 -I"$(SRCDIR)/nauty" -I"$(SRCDIR)/src"
# CXXFLAGS= -g -I"$(SRCDIR)/nauty" -I"$(SRCDIR)/src"

CFLAGS = -O3
